#!/bin/bash

INSTALLNAMETOOL=`which install_name_tool` # Fixes Mac OS X issue with linking.
ZNCBUILD=`which znc-buildmod`

if [ -f logMySQL.buildconfig ]; then
	. ./logMySQL.buildconfig
fi

if [ "$ZNCBUILD" = "" ]; then
	echo "Where is znc-buildmod:"
	read ZNCBUILD
	if [ "$ZNCBUILD" = "" ]; then
		exit
	fi
fi

if [ "$MYSQL" = "" ]; then
	echo "Where is MySQL path [/usr/local/mysql]:"
	read MYSQL
	if [ "$MYSQL" = "" ]; then
		MYSQL="/usr/local/mysql"
	fi
fi

if [ "$ZNCCONFIG" = "" ]; then
	echo "Where is ZNC configuration path [$HOME/.znc]:"
	read ZNCCONFIG
	if [ "$ZNCCONFIG" = "" ]; then
		ZNCCONFIG="$HOME/.znc"
	fi
fi

if [ ! -f logMySQL.buildconfig ]; then
	echo "#!/bin/bash" > logMySQL.buildconfig
	echo "ZNCBUILD=\"$ZNCBUILD\"" >> logMySQL.buildconfig
	echo "MYSQL=\"$MYSQL\"" >> logMySQL.buildconfig
	echo "ZNCCONFIG=\"$ZNCCONFIG\"" >> logMySQL.buildconfig
	chmod 755 logMySQL.buildconfig
fi

LDFLAGS="-L $MYSQL/lib -lmysqlclient -I $MYSQL/include" "$ZNCBUILD" logmysql.cpp
if [ "$INSTALLNAMETOOL" != "" ]; then
	"$INSTALLNAMETOOL" -change libmysqlclient.18.dylib "$MYSQL/libmysqlclient.dylib" logmysql.so
fi
cp logmysql.so "$ZNCCONFIG/modules/logmysql.so"